version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_c
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
  
  json-server:
    image: "node:18-alpine"
    command: "json-server --watch db.json --port 4000"
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      - app
